import clsx from "clsx";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={clsx("font-baseFont", "bg-base text-base")}>
        {children}
      </body>
    </html>
  );
}
