/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiBlogRouteImport } from './routes/api/blog'
import { Route as ApiDurableSignalingRouteImport } from './routes/api/durable-signaling'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiSourceRouteImport } from './routes/api/source'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as DemosIndexRouteImport } from './routes/demos/index'
import { Route as DemosBankRouteImport } from './routes/demos/bank'
import { Route as DemosDurableWebrtcRouteImport } from './routes/demos/durable-webrtc'
import { Route as DemosEffectWebrtcRouteImport } from './routes/demos/effect-webrtc'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogRoute = ApiBlogRouteImport.update({
  id: '/api/blog',
  path: '/api/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDurableSignalingRoute = ApiDurableSignalingRouteImport.update({
  id: '/api/durable-signaling',
  path: '/api/durable-signaling',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSourceRoute = ApiSourceRouteImport.update({
  id: '/api/source',
  path: '/api/source',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosIndexRoute = DemosIndexRouteImport.update({
  id: '/demos/',
  path: '/demos/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosBankRoute = DemosBankRouteImport.update({
  id: '/demos/bank',
  path: '/demos/bank',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosDurableWebrtcRoute = DemosDurableWebrtcRouteImport.update({
  id: '/demos/durable-webrtc',
  path: '/demos/durable-webrtc',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosEffectWebrtcRoute = DemosEffectWebrtcRouteImport.update({
  id: '/demos/effect-webrtc',
  path: '/demos/effect-webrtc',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/blog': typeof ApiBlogRoute
  '/api/durable-signaling': typeof ApiDurableSignalingRoute
  '/api/search': typeof ApiSearchRoute
  '/api/source': typeof ApiSourceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/demos/bank': typeof DemosBankRoute
  '/demos/durable-webrtc': typeof DemosDurableWebrtcRoute
  '/demos/effect-webrtc': typeof DemosEffectWebrtcRoute
  '/docs/$': typeof DocsSplatRoute
  '/blog/': typeof BlogIndexRoute
  '/demos/': typeof DemosIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/blog': typeof ApiBlogRoute
  '/api/durable-signaling': typeof ApiDurableSignalingRoute
  '/api/search': typeof ApiSearchRoute
  '/api/source': typeof ApiSourceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/demos/bank': typeof DemosBankRoute
  '/demos/durable-webrtc': typeof DemosDurableWebrtcRoute
  '/demos/effect-webrtc': typeof DemosEffectWebrtcRoute
  '/docs/$': typeof DocsSplatRoute
  '/blog': typeof BlogIndexRoute
  '/demos': typeof DemosIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/blog': typeof ApiBlogRoute
  '/api/durable-signaling': typeof ApiDurableSignalingRoute
  '/api/search': typeof ApiSearchRoute
  '/api/source': typeof ApiSourceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/demos/bank': typeof DemosBankRoute
  '/demos/durable-webrtc': typeof DemosDurableWebrtcRoute
  '/demos/effect-webrtc': typeof DemosEffectWebrtcRoute
  '/docs/$': typeof DocsSplatRoute
  '/blog/': typeof BlogIndexRoute
  '/demos/': typeof DemosIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/blog'
    | '/api/durable-signaling'
    | '/api/search'
    | '/api/source'
    | '/blog/$slug'
    | '/demos/bank'
    | '/demos/durable-webrtc'
    | '/demos/effect-webrtc'
    | '/docs/$'
    | '/blog/'
    | '/demos/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/blog'
    | '/api/durable-signaling'
    | '/api/search'
    | '/api/source'
    | '/blog/$slug'
    | '/demos/bank'
    | '/demos/durable-webrtc'
    | '/demos/effect-webrtc'
    | '/docs/$'
    | '/blog'
    | '/demos'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/api/blog'
    | '/api/durable-signaling'
    | '/api/search'
    | '/api/source'
    | '/blog/$slug'
    | '/demos/bank'
    | '/demos/durable-webrtc'
    | '/demos/effect-webrtc'
    | '/docs/$'
    | '/blog/'
    | '/demos/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiBlogRoute: typeof ApiBlogRoute
  ApiDurableSignalingRoute: typeof ApiDurableSignalingRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiSourceRoute: typeof ApiSourceRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DemosBankRoute: typeof DemosBankRoute
  DemosDurableWebrtcRoute: typeof DemosDurableWebrtcRoute
  DemosEffectWebrtcRoute: typeof DemosEffectWebrtcRoute
  DocsSplatRoute: typeof DocsSplatRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DemosIndexRoute: typeof DemosIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blog': {
      id: '/api/blog'
      path: '/api/blog'
      fullPath: '/api/blog'
      preLoaderRoute: typeof ApiBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/durable-signaling': {
      id: '/api/durable-signaling'
      path: '/api/durable-signaling'
      fullPath: '/api/durable-signaling'
      preLoaderRoute: typeof ApiDurableSignalingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/source': {
      id: '/api/source'
      path: '/api/source'
      fullPath: '/api/source'
      preLoaderRoute: typeof ApiSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/': {
      id: '/demos/'
      path: '/demos'
      fullPath: '/demos/'
      preLoaderRoute: typeof DemosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/bank': {
      id: '/demos/bank'
      path: '/demos/bank'
      fullPath: '/demos/bank'
      preLoaderRoute: typeof DemosBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/durable-webrtc': {
      id: '/demos/durable-webrtc'
      path: '/demos/durable-webrtc'
      fullPath: '/demos/durable-webrtc'
      preLoaderRoute: typeof DemosDurableWebrtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/effect-webrtc': {
      id: '/demos/effect-webrtc'
      path: '/demos/effect-webrtc'
      fullPath: '/demos/effect-webrtc'
      preLoaderRoute: typeof DemosEffectWebrtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiBlogRoute: ApiBlogRoute,
  ApiDurableSignalingRoute: ApiDurableSignalingRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiSourceRoute: ApiSourceRoute,
  BlogSlugRoute: BlogSlugRoute,
  DemosBankRoute: DemosBankRoute,
  DemosDurableWebrtcRoute: DemosDurableWebrtcRoute,
  DemosEffectWebrtcRoute: DemosEffectWebrtcRoute,
  DocsSplatRoute: DocsSplatRoute,
  BlogIndexRoute: BlogIndexRoute,
  DemosIndexRoute: DemosIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
