export {
  Table,
  type AccessPatternDefinition,
  type AccessPatternMap,
  type GlobalSecondaryIndex,
  type GlobalSecondaryIndexMap,
  type IndexComponent,
  type KeyPath,
  type KeyPathValue,
  type KeyRecord,
  type KeyedEntityBuilder,
  type KeyedEntityBuilderStart,
  type KeyedEntityDefinition,
  type LocalSecondaryIndex,
  type LocalSecondaryIndexMap,
  type PatternFor,
  type PrimaryComponent,
  type PrimaryIndex,
  type SingleEntityBuilder,
  type SingleEntityDefinition,
  type TableBuilder,
  type TableDefinition,
  type TableTopologyBuilder,
  type TotalKeyPath,
} from './definition.js';
export { keyPathKind } from './key-path-shape.js';
