export {
  Table,
  type AccessPatternDefinition,
  type AccessPatternMap,
  type GlobalSecondaryIndex,
  type GlobalSecondaryIndexMap,
  type IndexComponent,
  type KeyedEntityBuilder,
  type KeyedEntityBuilderStart,
  type KeyedEntityDefinition,
  type LocalSecondaryIndex,
  type LocalSecondaryIndexMap,
  type LogicalEntitySnapshot,
  type LogicalTableSnapshot,
  type PatternFor,
  type PrimaryIndex,
  type SingleEntityBuilder,
  type SingleEntityDefinition,
  type TableBuilder,
  type TableDefinition,
  type TableTopologyBuilder,
} from './definition.js';
