// Runs after `vite build`: embeds the client assets and wraps the Start
// server bundle so `auth-toolkit/worker` can serve the pages itself.
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { extname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../dist/app/', import.meta.url));
const client = join(root, 'client');

const TEXT = new Map([
  ['.js', 'text/javascript; charset=utf-8'],
  ['.css', 'text/css; charset=utf-8'],
  ['.svg', 'image/svg+xml'],
  ['.json', 'application/json'],
  ['.txt', 'text/plain; charset=utf-8'],
]);
const BINARY = new Map([
  ['.woff2', 'font/woff2'],
  ['.woff', 'font/woff'],
  ['.png', 'image/png'],
  ['.ico', 'image/x-icon'],
]);

const walk = (dir: string): string[] =>
  readdirSync(dir).flatMap((name) => {
    const path = join(dir, name);
    return statSync(path).isDirectory() ? walk(path) : [path];
  });

// workerd has no import.meta.url, so a CommonJS dependency inlined next to an
// external `require` crashes every request. Keep such packages external by
// listing them as dependencies of this package.
const requiring = walk(join(root, 'server')).filter((path) =>
  readFileSync(path, 'utf8').includes('createRequire('),
);
if (requiring.length > 0) {
  throw new Error(
    `The server bundle calls createRequire, which fails in workerd: ${requiring.map((path) => relative(root, path)).join(', ')}`,
  );
}

const entries = walk(client)
  .filter((path) => !path.endsWith('.html'))
  .map((path) => {
    const ext = extname(path);
    const url = `/${relative(client, path)}`;
    const text = TEXT.get(ext);
    const binary = BINARY.get(ext);
    if (text) {
      return `  ${JSON.stringify(url)}: { type: ${JSON.stringify(text)}, body: ${JSON.stringify(readFileSync(path).toString('utf8'))} },`;
    }
    if (binary) {
      return `  ${JSON.stringify(url)}: { type: ${JSON.stringify(binary)}, base64: ${JSON.stringify(readFileSync(path).toString('base64'))} },`;
    }
    throw new Error(`No content type for ${url}`);
  });

writeFileSync(
  join(root, 'assets.js'),
  `// Generated by scripts/bundle-app.mts. Do not edit.\nexport const assets = {\n${entries.join('\n')}\n};\n`,
);

writeFileSync(
  join(root, 'worker.js'),
  `// Generated by scripts/bundle-app.mts. Do not edit.
// The runtime of \`auth-toolkit/worker\`: the source createAuthWorker paired
// with the Start pages app and its embedded assets. Types come from
// dist/worker/index.d.ts.
import pages from './server/server.js';
import { assets } from './assets.js';
import { createAuthWorker as base } from '../worker/index.js';

export * from '../worker/index.js';
export const createAuthWorker = (config) =>
  base({ ...config, pages: { fetch: pages, assets } });
`,
);
console.log(`embedded ${entries.length} assets into dist/app/assets.js`);
