export {
  ConditionFailed,
  DatabaseError,
  DecodeFailed,
  DuplicateTransactionTarget,
  ForeignTransactionItem,
  InvalidQuery,
  ItemAlreadyExists,
  NoItemToUpdate,
  OperationFailed,
  PrimaryKeyUpdateNotSupported,
  TransactFailed,
  TransactionTooLarge,
  UpdateRefused,
  type DatabaseErrorReason,
  type TransactOperation,
  type TransactOutcome,
} from './error.js';
