export {
  DynamoDBClientError,
  makeDynamoDBClient,
  type AttributeValue,
  type BatchWriteItemOutput,
  type CreateTableInput,
  type DynamoDBClient,
  type DynamoDBClientConfig,
  type DynamoDBCredentialProvider,
  type DynamoDBCredentials,
  type DynamoDBCredentialsInput,
  type GetItemOutput,
  type ScanOutput,
  type TransactWriteItem,
  type UpdateItemOutput,
} from './client.js';
