export {
  compareStrings,
  ContractSnapshotSchema,
  ESchemaDefinitionSchema,
  ESchemaSnapshotSchema,
  ESchemaVersionSchema,
  SnapshotChangeSchema,
  SnapshotClassificationSchema,
  SnapshotDecodeError,
  SnapshotDiagnosticSchema,
  SnapshotFormatRetired,
  SnapshotIdentityConflict,
  SnapshotMarkerSchema,
  SnapshotScopeSchema,
  SnapshotTransformationSchema,
  stableStringify,
  TableAccessPatternSnapshotSchema,
  TableEntityDerivationSnapshotSchema,
  TableEntitySnapshotSchema,
  TableIndexSnapshotSchema,
  TableSnapshotSchema,
  TableTopologySnapshotSchema,
} from './domain.js';
export type * from './domain.js';
