/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevtoolsIndexRouteImport } from './routes/devtools/index'
import { Route as DevIndexRouteImport } from './routes/dev/index'
import { Route as DevUiRouteImport } from './routes/dev/ui'
import { Route as DevFormsRouteImport } from './routes/dev/forms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevtoolsIndexRoute = DevtoolsIndexRouteImport.update({
  id: '/devtools/',
  path: '/devtools/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevIndexRoute = DevIndexRouteImport.update({
  id: '/dev/',
  path: '/dev/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevUiRoute = DevUiRouteImport.update({
  id: '/dev/ui',
  path: '/dev/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const DevFormsRoute = DevFormsRouteImport.update({
  id: '/dev/forms',
  path: '/dev/forms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev/forms': typeof DevFormsRoute
  '/dev/ui': typeof DevUiRoute
  '/dev/': typeof DevIndexRoute
  '/devtools/': typeof DevtoolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev/forms': typeof DevFormsRoute
  '/dev/ui': typeof DevUiRoute
  '/dev': typeof DevIndexRoute
  '/devtools': typeof DevtoolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dev/forms': typeof DevFormsRoute
  '/dev/ui': typeof DevUiRoute
  '/dev/': typeof DevIndexRoute
  '/devtools/': typeof DevtoolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dev/forms' | '/dev/ui' | '/dev/' | '/devtools/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dev/forms' | '/dev/ui' | '/dev' | '/devtools'
  id: '__root__' | '/' | '/dev/forms' | '/dev/ui' | '/dev/' | '/devtools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevFormsRoute: typeof DevFormsRoute
  DevUiRoute: typeof DevUiRoute
  DevIndexRoute: typeof DevIndexRoute
  DevtoolsIndexRoute: typeof DevtoolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devtools/': {
      id: '/devtools/'
      path: '/devtools'
      fullPath: '/devtools/'
      preLoaderRoute: typeof DevtoolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/': {
      id: '/dev/'
      path: '/dev'
      fullPath: '/dev/'
      preLoaderRoute: typeof DevIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/ui': {
      id: '/dev/ui'
      path: '/dev/ui'
      fullPath: '/dev/ui'
      preLoaderRoute: typeof DevUiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/forms': {
      id: '/dev/forms'
      path: '/dev/forms'
      fullPath: '/dev/forms'
      preLoaderRoute: typeof DevFormsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevFormsRoute: DevFormsRoute,
  DevUiRoute: DevUiRoute,
  DevIndexRoute: DevIndexRoute,
  DevtoolsIndexRoute: DevtoolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
