export {
  compareStrings,
  ESchemaDefinitionSchema,
  ESchemaVersionSchema,
  JsonValueSchema,
  SnapshotChangeSchema,
  SnapshotImpactSchema,
  SnapshotDecodeError,
  SnapshotDiagnosticSchema,
  SnapshotIdentityConflict,
  SnapshotIncompatible,
  SnapshotMarkerSchema,
  SnapshotEditSchema,
  SnapshotSubjectKindSchema,
  SnapshotSubjectSchema,
  SnapshotTransformationSchema,
  stableStringify,
  TableAccessPatternSnapshotSchema,
  TableEntityDerivationSnapshotSchema,
  TableEntitySnapshotSchema,
  TableIndexSnapshotSchema,
  TableSnapshotESchema,
  tableSnapshotIssues,
  TableTopologySnapshotSchema,
} from './domain.js';
export type * from './domain.js';
