import { useTheme } from 'next-themes';
import { useEffect, useRef, useState } from 'react';

let mermaidPromise: Promise<typeof import('mermaid').default> | null = null;
const loadMermaid = (): Promise<typeof import('mermaid').default> => {
  if (!mermaidPromise) {
    mermaidPromise = import('mermaid').then((m) => m.default);
  }
  return mermaidPromise;
};

const darkVars = {
  darkMode: true,
  background: 'transparent',
  primaryColor: '#1e293b',
  primaryTextColor: '#e2e8f0',
  primaryBorderColor: '#475569',
  secondaryColor: '#334155',
  tertiaryColor: '#0f172a',
  lineColor: '#64748b',
  textColor: '#e2e8f0',
  mainBkg: '#1e293b',
  secondBkg: '#334155',
  nodeBorder: '#475569',
  clusterBkg: '#0f172a',
  clusterBorder: '#334155',
  edgeLabelBackground: '#0f172a',
  labelBackground: '#0f172a',
  labelTextColor: '#e2e8f0',
};

const lightVars = {
  darkMode: false,
  background: 'transparent',
  primaryColor: '#f8fafc',
  primaryTextColor: '#0f172a',
  primaryBorderColor: '#cbd5e1',
  secondaryColor: '#e2e8f0',
  tertiaryColor: '#f1f5f9',
  lineColor: '#64748b',
  textColor: '#0f172a',
  mainBkg: '#f8fafc',
  secondBkg: '#e2e8f0',
  nodeBorder: '#cbd5e1',
  clusterBkg: '#f1f5f9',
  clusterBorder: '#cbd5e1',
  edgeLabelBackground: '#ffffff',
  labelBackground: '#ffffff',
  labelTextColor: '#0f172a',
};

let counter = 0;

export function Mermaid({ value }: { value: string }) {
  const { resolvedTheme } = useTheme();
  const [svg, setSvg] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const idRef = useRef(`mmd-${++counter}`);
  const isDark = resolvedTheme !== 'light';

  useEffect(() => {
    let cancelled = false;
    loadMermaid()
      .then((m) => {
        m.initialize({
          startOnLoad: false,
          theme: 'base',
          themeVariables: isDark ? darkVars : lightVars,
        });
        return m.render(`${idRef.current}-${isDark ? 'd' : 'l'}`, value);
      })
      .then(({ svg: rendered }) => {
        if (!cancelled) setSvg(rendered);
      })
      .catch((e: unknown) => {
        if (!cancelled) setError(e instanceof Error ? e.message : String(e));
      });
    return () => {
      cancelled = true;
    };
  }, [value, isDark]);

  if (error) {
    return (
      <pre className="overflow-x-auto rounded-md border border-red-500/30 bg-red-500/5 p-3 text-xs text-red-400">
        {`mermaid error: ${error}\n\n${value}`}
      </pre>
    );
  }

  if (!svg) {
    return (
      <div className="text-muted-foreground bg-card/40 rounded-md border p-3 text-xs">
        Rendering diagram…
      </div>
    );
  }

  return (
    <div
      className="bg-card/40 my-3 flex justify-center overflow-x-auto rounded-md border p-3"
      // svg is generated by mermaid from author-controlled markdown
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
