/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSimRouteImport } from './routes/auth-sim'
import { Route as DataRouteImport } from './routes/data'
import { Route as InstallRouteImport } from './routes/install'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as RpcRouteImport } from './routes/rpc'
import { Route as RuntimeCacheRouteImport } from './routes/runtime-cache'
import { Route as StatusRouteImport } from './routes/status'
import { Route as UpdateRouteImport } from './routes/update'
import { Route as ApiDataRouteImport } from './routes/api/data'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiTimeStrategyRouteImport } from './routes/api/time/$strategy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSimRoute = AuthSimRouteImport.update({
  id: '/auth-sim',
  path: '/auth-sim',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const RpcRoute = RpcRouteImport.update({
  id: '/rpc',
  path: '/rpc',
  getParentRoute: () => rootRouteImport,
} as any)
const RuntimeCacheRoute = RuntimeCacheRouteImport.update({
  id: '/runtime-cache',
  path: '/runtime-cache',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdateRoute = UpdateRouteImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataRoute = ApiDataRouteImport.update({
  id: '/api/data',
  path: '/api/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTimeStrategyRoute = ApiTimeStrategyRouteImport.update({
  id: '/api/time/$strategy',
  path: '/api/time/$strategy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth-sim': typeof AuthSimRoute
  '/data': typeof DataRoute
  '/install': typeof InstallRoute
  '/offline': typeof OfflineRoute
  '/rpc': typeof RpcRoute
  '/runtime-cache': typeof RuntimeCacheRoute
  '/status': typeof StatusRoute
  '/update': typeof UpdateRoute
  '/api/data': typeof ApiDataRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/time/$strategy': typeof ApiTimeStrategyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth-sim': typeof AuthSimRoute
  '/data': typeof DataRoute
  '/install': typeof InstallRoute
  '/offline': typeof OfflineRoute
  '/rpc': typeof RpcRoute
  '/runtime-cache': typeof RuntimeCacheRoute
  '/status': typeof StatusRoute
  '/update': typeof UpdateRoute
  '/api/data': typeof ApiDataRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/time/$strategy': typeof ApiTimeStrategyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth-sim': typeof AuthSimRoute
  '/data': typeof DataRoute
  '/install': typeof InstallRoute
  '/offline': typeof OfflineRoute
  '/rpc': typeof RpcRoute
  '/runtime-cache': typeof RuntimeCacheRoute
  '/status': typeof StatusRoute
  '/update': typeof UpdateRoute
  '/api/data': typeof ApiDataRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/time/$strategy': typeof ApiTimeStrategyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth-sim'
    | '/data'
    | '/install'
    | '/offline'
    | '/rpc'
    | '/runtime-cache'
    | '/status'
    | '/update'
    | '/api/data'
    | '/api/auth/session'
    | '/api/time/$strategy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth-sim'
    | '/data'
    | '/install'
    | '/offline'
    | '/rpc'
    | '/runtime-cache'
    | '/status'
    | '/update'
    | '/api/data'
    | '/api/auth/session'
    | '/api/time/$strategy'
  id:
    | '__root__'
    | '/'
    | '/auth-sim'
    | '/data'
    | '/install'
    | '/offline'
    | '/rpc'
    | '/runtime-cache'
    | '/status'
    | '/update'
    | '/api/data'
    | '/api/auth/session'
    | '/api/time/$strategy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthSimRoute: typeof AuthSimRoute
  DataRoute: typeof DataRoute
  InstallRoute: typeof InstallRoute
  OfflineRoute: typeof OfflineRoute
  RpcRoute: typeof RpcRoute
  RuntimeCacheRoute: typeof RuntimeCacheRoute
  StatusRoute: typeof StatusRoute
  UpdateRoute: typeof UpdateRoute
  ApiDataRoute: typeof ApiDataRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiTimeStrategyRoute: typeof ApiTimeStrategyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-sim': {
      id: '/auth-sim'
      path: '/auth-sim'
      fullPath: '/auth-sim'
      preLoaderRoute: typeof AuthSimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rpc': {
      id: '/rpc'
      path: '/rpc'
      fullPath: '/rpc'
      preLoaderRoute: typeof RpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runtime-cache': {
      id: '/runtime-cache'
      path: '/runtime-cache'
      fullPath: '/runtime-cache'
      preLoaderRoute: typeof RuntimeCacheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update': {
      id: '/update'
      path: '/update'
      fullPath: '/update'
      preLoaderRoute: typeof UpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data': {
      id: '/api/data'
      path: '/api/data'
      fullPath: '/api/data'
      preLoaderRoute: typeof ApiDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/time/$strategy': {
      id: '/api/time/$strategy'
      path: '/api/time/$strategy'
      fullPath: '/api/time/$strategy'
      preLoaderRoute: typeof ApiTimeStrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthSimRoute: AuthSimRoute,
  DataRoute: DataRoute,
  InstallRoute: InstallRoute,
  OfflineRoute: OfflineRoute,
  RpcRoute: RpcRoute,
  RuntimeCacheRoute: RuntimeCacheRoute,
  StatusRoute: StatusRoute,
  UpdateRoute: UpdateRoute,
  ApiDataRoute: ApiDataRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiTimeStrategyRoute: ApiTimeStrategyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
