export {
  BatchWriteFailed,
  ConditionCheckFailed,
  ConditionFailed,
  DeleteItemFailed,
  DescribeFailed,
  DuplicateTableBinding,
  DuplicateTransactionTarget,
  DynamoDBError,
  extractConditionFailureItem,
  ForeignTransactionItem,
  GetItemFailed,
  IdUpdateNotSupported,
  ItemAlreadyExists,
  ItemMigrationFailed,
  ItemVersionMismatch,
  isConditionalCheckFailed,
  NoItemToDelete,
  NoItemToRestore,
  NoItemToUpdate,
  PutItemFailed,
  QueryFailed,
  ScanFailed,
  TableBindingNotFound,
  TransactionFailed,
  UpdateItemFailed,
  type TransactionFailureContext,
} from './dynamodb-error.js';
