/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LedgerRouteRouteImport } from './routes/_ledger/route'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as LedgerIndexRouteImport } from './routes/_ledger/index'
import { Route as LedgerEntriesRouteRouteImport } from './routes/_ledger/entries/route'
import { Route as LedgerSettingsRouteImport } from './routes/_ledger/settings'
import { Route as LedgerEntriesIndexRouteImport } from './routes/_ledger/entries/index'
import { Route as LedgerEntriesEntryIdRouteImport } from './routes/_ledger/entries/$entryId'
import { Route as LedgerMonthsIndexRouteImport } from './routes/_ledger/months/index'
import { Route as LedgerMonthsMonthRouteImport } from './routes/_ledger/months/$month'

const LedgerRouteRoute = LedgerRouteRouteImport.update({
  id: '/_ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerIndexRoute = LedgerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LedgerRouteRoute,
} as any)
const LedgerEntriesRouteRoute = LedgerEntriesRouteRouteImport.update({
  id: '/entries',
  path: '/entries',
  getParentRoute: () => LedgerRouteRoute,
} as any)
const LedgerSettingsRoute = LedgerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LedgerRouteRoute,
} as any)
const LedgerEntriesIndexRoute = LedgerEntriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LedgerEntriesRouteRoute,
} as any)
const LedgerEntriesEntryIdRoute = LedgerEntriesEntryIdRouteImport.update({
  id: '/$entryId',
  path: '/$entryId',
  getParentRoute: () => LedgerEntriesRouteRoute,
} as any)
const LedgerMonthsIndexRoute = LedgerMonthsIndexRouteImport.update({
  id: '/months/',
  path: '/months/',
  getParentRoute: () => LedgerRouteRoute,
} as any)
const LedgerMonthsMonthRoute = LedgerMonthsMonthRouteImport.update({
  id: '/months/$month',
  path: '/months/$month',
  getParentRoute: () => LedgerRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LedgerIndexRoute
  '/offline': typeof OfflineRoute
  '/entries': typeof LedgerEntriesRouteRouteWithChildren
  '/settings': typeof LedgerSettingsRoute
  '/entries/$entryId': typeof LedgerEntriesEntryIdRoute
  '/months/$month': typeof LedgerMonthsMonthRoute
  '/entries/': typeof LedgerEntriesIndexRoute
  '/months/': typeof LedgerMonthsIndexRoute
}
export interface FileRoutesByTo {
  '/offline': typeof OfflineRoute
  '/settings': typeof LedgerSettingsRoute
  '/': typeof LedgerIndexRoute
  '/entries/$entryId': typeof LedgerEntriesEntryIdRoute
  '/months/$month': typeof LedgerMonthsMonthRoute
  '/entries': typeof LedgerEntriesIndexRoute
  '/months': typeof LedgerMonthsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_ledger': typeof LedgerRouteRouteWithChildren
  '/offline': typeof OfflineRoute
  '/_ledger/entries': typeof LedgerEntriesRouteRouteWithChildren
  '/_ledger/settings': typeof LedgerSettingsRoute
  '/_ledger/': typeof LedgerIndexRoute
  '/_ledger/entries/$entryId': typeof LedgerEntriesEntryIdRoute
  '/_ledger/months/$month': typeof LedgerMonthsMonthRoute
  '/_ledger/entries/': typeof LedgerEntriesIndexRoute
  '/_ledger/months/': typeof LedgerMonthsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/offline'
    | '/entries'
    | '/settings'
    | '/entries/$entryId'
    | '/months/$month'
    | '/entries/'
    | '/months/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/offline'
    | '/settings'
    | '/'
    | '/entries/$entryId'
    | '/months/$month'
    | '/entries'
    | '/months'
  id:
    | '__root__'
    | '/_ledger'
    | '/offline'
    | '/_ledger/entries'
    | '/_ledger/settings'
    | '/_ledger/'
    | '/_ledger/entries/$entryId'
    | '/_ledger/months/$month'
    | '/_ledger/entries/'
    | '/_ledger/months/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LedgerRouteRoute: typeof LedgerRouteRouteWithChildren
  OfflineRoute: typeof OfflineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_ledger': {
      id: '/_ledger'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LedgerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_ledger/': {
      id: '/_ledger/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LedgerIndexRouteImport
      parentRoute: typeof LedgerRouteRoute
    }
    '/_ledger/entries': {
      id: '/_ledger/entries'
      path: '/entries'
      fullPath: '/entries'
      preLoaderRoute: typeof LedgerEntriesRouteRouteImport
      parentRoute: typeof LedgerRouteRoute
    }
    '/_ledger/settings': {
      id: '/_ledger/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LedgerSettingsRouteImport
      parentRoute: typeof LedgerRouteRoute
    }
    '/_ledger/entries/': {
      id: '/_ledger/entries/'
      path: '/'
      fullPath: '/entries/'
      preLoaderRoute: typeof LedgerEntriesIndexRouteImport
      parentRoute: typeof LedgerEntriesRouteRoute
    }
    '/_ledger/entries/$entryId': {
      id: '/_ledger/entries/$entryId'
      path: '/$entryId'
      fullPath: '/entries/$entryId'
      preLoaderRoute: typeof LedgerEntriesEntryIdRouteImport
      parentRoute: typeof LedgerEntriesRouteRoute
    }
    '/_ledger/months/': {
      id: '/_ledger/months/'
      path: '/months'
      fullPath: '/months/'
      preLoaderRoute: typeof LedgerMonthsIndexRouteImport
      parentRoute: typeof LedgerRouteRoute
    }
    '/_ledger/months/$month': {
      id: '/_ledger/months/$month'
      path: '/months/$month'
      fullPath: '/months/$month'
      preLoaderRoute: typeof LedgerMonthsMonthRouteImport
      parentRoute: typeof LedgerRouteRoute
    }
  }
}

interface LedgerEntriesRouteRouteChildren {
  LedgerEntriesEntryIdRoute: typeof LedgerEntriesEntryIdRoute
  LedgerEntriesIndexRoute: typeof LedgerEntriesIndexRoute
}

const LedgerEntriesRouteRouteChildren: LedgerEntriesRouteRouteChildren = {
  LedgerEntriesEntryIdRoute: LedgerEntriesEntryIdRoute,
  LedgerEntriesIndexRoute: LedgerEntriesIndexRoute,
}

const LedgerEntriesRouteRouteWithChildren =
  LedgerEntriesRouteRoute._addFileChildren(LedgerEntriesRouteRouteChildren)

interface LedgerRouteRouteChildren {
  LedgerEntriesRouteRoute: typeof LedgerEntriesRouteRouteWithChildren
  LedgerSettingsRoute: typeof LedgerSettingsRoute
  LedgerIndexRoute: typeof LedgerIndexRoute
  LedgerMonthsMonthRoute: typeof LedgerMonthsMonthRoute
  LedgerMonthsIndexRoute: typeof LedgerMonthsIndexRoute
}

const LedgerRouteRouteChildren: LedgerRouteRouteChildren = {
  LedgerEntriesRouteRoute: LedgerEntriesRouteRouteWithChildren,
  LedgerSettingsRoute: LedgerSettingsRoute,
  LedgerIndexRoute: LedgerIndexRoute,
  LedgerMonthsMonthRoute: LedgerMonthsMonthRoute,
  LedgerMonthsIndexRoute: LedgerMonthsIndexRoute,
}

const LedgerRouteRouteWithChildren = LedgerRouteRoute._addFileChildren(
  LedgerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LedgerRouteRoute: LedgerRouteRouteWithChildren,
  OfflineRoute: OfflineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
