/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppShellRouteRouteImport } from './routes/app-shell/route'
import { Route as GesturesRouteRouteImport } from './routes/gestures/route'
import { Route as KeyboardRouteImport } from './routes/keyboard'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as AppShellIndexRouteImport } from './routes/app-shell/index'
import { Route as AppShellSectionRouteImport } from './routes/app-shell/$section'
import { Route as FeaturesIndexRouteImport } from './routes/features/index'
import { Route as FeaturesFeatureRouteImport } from './routes/features/$feature'
import { Route as GesturesIndexRouteImport } from './routes/gestures/index'
import { Route as GesturesTopicRouteImport } from './routes/gestures/$topic'
import { Route as GesturesTopicScenarioRouteImport } from './routes/gestures_.$topic.$scenario'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppShellRouteRoute = AppShellRouteRouteImport.update({
  id: '/app-shell',
  path: '/app-shell',
  getParentRoute: () => rootRouteImport,
} as any)
const GesturesRouteRoute = GesturesRouteRouteImport.update({
  id: '/gestures',
  path: '/gestures',
  getParentRoute: () => rootRouteImport,
} as any)
const KeyboardRoute = KeyboardRouteImport.update({
  id: '/keyboard',
  path: '/keyboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const AppShellIndexRoute = AppShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppShellRouteRoute,
} as any)
const AppShellSectionRoute = AppShellSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AppShellRouteRoute,
} as any)
const FeaturesIndexRoute = FeaturesIndexRouteImport.update({
  id: '/features/',
  path: '/features/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesFeatureRoute = FeaturesFeatureRouteImport.update({
  id: '/features/$feature',
  path: '/features/$feature',
  getParentRoute: () => rootRouteImport,
} as any)
const GesturesIndexRoute = GesturesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GesturesRouteRoute,
} as any)
const GesturesTopicRoute = GesturesTopicRouteImport.update({
  id: '/$topic',
  path: '/$topic',
  getParentRoute: () => GesturesRouteRoute,
} as any)
const GesturesTopicScenarioRoute = GesturesTopicScenarioRouteImport.update({
  id: '/gestures_/$topic/$scenario',
  path: '/gestures/$topic/$scenario',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app-shell': typeof AppShellRouteRouteWithChildren
  '/gestures': typeof GesturesRouteRouteWithChildren
  '/keyboard': typeof KeyboardRoute
  '/offline': typeof OfflineRoute
  '/app-shell/$section': typeof AppShellSectionRoute
  '/features/$feature': typeof FeaturesFeatureRoute
  '/gestures/$topic': typeof GesturesTopicRoute
  '/app-shell/': typeof AppShellIndexRoute
  '/features/': typeof FeaturesIndexRoute
  '/gestures/': typeof GesturesIndexRoute
  '/gestures/$topic/$scenario': typeof GesturesTopicScenarioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/keyboard': typeof KeyboardRoute
  '/offline': typeof OfflineRoute
  '/app-shell/$section': typeof AppShellSectionRoute
  '/features/$feature': typeof FeaturesFeatureRoute
  '/gestures/$topic': typeof GesturesTopicRoute
  '/app-shell': typeof AppShellIndexRoute
  '/features': typeof FeaturesIndexRoute
  '/gestures': typeof GesturesIndexRoute
  '/gestures/$topic/$scenario': typeof GesturesTopicScenarioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app-shell': typeof AppShellRouteRouteWithChildren
  '/gestures': typeof GesturesRouteRouteWithChildren
  '/keyboard': typeof KeyboardRoute
  '/offline': typeof OfflineRoute
  '/app-shell/$section': typeof AppShellSectionRoute
  '/features/$feature': typeof FeaturesFeatureRoute
  '/gestures/$topic': typeof GesturesTopicRoute
  '/app-shell/': typeof AppShellIndexRoute
  '/features/': typeof FeaturesIndexRoute
  '/gestures/': typeof GesturesIndexRoute
  '/gestures_/$topic/$scenario': typeof GesturesTopicScenarioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app-shell'
    | '/gestures'
    | '/keyboard'
    | '/offline'
    | '/app-shell/$section'
    | '/features/$feature'
    | '/gestures/$topic'
    | '/app-shell/'
    | '/features/'
    | '/gestures/'
    | '/gestures/$topic/$scenario'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/keyboard'
    | '/offline'
    | '/app-shell/$section'
    | '/features/$feature'
    | '/gestures/$topic'
    | '/app-shell'
    | '/features'
    | '/gestures'
    | '/gestures/$topic/$scenario'
  id:
    | '__root__'
    | '/'
    | '/app-shell'
    | '/gestures'
    | '/keyboard'
    | '/offline'
    | '/app-shell/$section'
    | '/features/$feature'
    | '/gestures/$topic'
    | '/app-shell/'
    | '/features/'
    | '/gestures/'
    | '/gestures_/$topic/$scenario'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppShellRouteRoute: typeof AppShellRouteRouteWithChildren
  GesturesRouteRoute: typeof GesturesRouteRouteWithChildren
  KeyboardRoute: typeof KeyboardRoute
  OfflineRoute: typeof OfflineRoute
  FeaturesFeatureRoute: typeof FeaturesFeatureRoute
  FeaturesIndexRoute: typeof FeaturesIndexRoute
  GesturesTopicScenarioRoute: typeof GesturesTopicScenarioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-shell': {
      id: '/app-shell'
      path: '/app-shell'
      fullPath: '/app-shell'
      preLoaderRoute: typeof AppShellRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestures': {
      id: '/gestures'
      path: '/gestures'
      fullPath: '/gestures'
      preLoaderRoute: typeof GesturesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keyboard': {
      id: '/keyboard'
      path: '/keyboard'
      fullPath: '/keyboard'
      preLoaderRoute: typeof KeyboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-shell/': {
      id: '/app-shell/'
      path: '/'
      fullPath: '/app-shell/'
      preLoaderRoute: typeof AppShellIndexRouteImport
      parentRoute: typeof AppShellRouteRoute
    }
    '/app-shell/$section': {
      id: '/app-shell/$section'
      path: '/$section'
      fullPath: '/app-shell/$section'
      preLoaderRoute: typeof AppShellSectionRouteImport
      parentRoute: typeof AppShellRouteRoute
    }
    '/features/': {
      id: '/features/'
      path: '/features'
      fullPath: '/features/'
      preLoaderRoute: typeof FeaturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/$feature': {
      id: '/features/$feature'
      path: '/features/$feature'
      fullPath: '/features/$feature'
      preLoaderRoute: typeof FeaturesFeatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestures/': {
      id: '/gestures/'
      path: '/'
      fullPath: '/gestures/'
      preLoaderRoute: typeof GesturesIndexRouteImport
      parentRoute: typeof GesturesRouteRoute
    }
    '/gestures/$topic': {
      id: '/gestures/$topic'
      path: '/$topic'
      fullPath: '/gestures/$topic'
      preLoaderRoute: typeof GesturesTopicRouteImport
      parentRoute: typeof GesturesRouteRoute
    }
    '/gestures_/$topic/$scenario': {
      id: '/gestures_/$topic/$scenario'
      path: '/gestures/$topic/$scenario'
      fullPath: '/gestures/$topic/$scenario'
      preLoaderRoute: typeof GesturesTopicScenarioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppShellRouteRouteChildren {
  AppShellSectionRoute: typeof AppShellSectionRoute
  AppShellIndexRoute: typeof AppShellIndexRoute
}

const AppShellRouteRouteChildren: AppShellRouteRouteChildren = {
  AppShellSectionRoute: AppShellSectionRoute,
  AppShellIndexRoute: AppShellIndexRoute,
}

const AppShellRouteRouteWithChildren = AppShellRouteRoute._addFileChildren(
  AppShellRouteRouteChildren,
)

interface GesturesRouteRouteChildren {
  GesturesTopicRoute: typeof GesturesTopicRoute
  GesturesIndexRoute: typeof GesturesIndexRoute
}

const GesturesRouteRouteChildren: GesturesRouteRouteChildren = {
  GesturesTopicRoute: GesturesTopicRoute,
  GesturesIndexRoute: GesturesIndexRoute,
}

const GesturesRouteRouteWithChildren = GesturesRouteRoute._addFileChildren(
  GesturesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppShellRouteRoute: AppShellRouteRouteWithChildren,
  GesturesRouteRoute: GesturesRouteRouteWithChildren,
  KeyboardRoute: KeyboardRoute,
  OfflineRoute: OfflineRoute,
  FeaturesFeatureRoute: FeaturesFeatureRoute,
  FeaturesIndexRoute: FeaturesIndexRoute,
  GesturesTopicScenarioRoute: GesturesTopicScenarioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
