/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppShellRouteRouteImport } from './routes/app-shell/route'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as AppShellIndexRouteImport } from './routes/app-shell/index'
import { Route as AppShellSectionRouteImport } from './routes/app-shell/$section'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppShellRouteRoute = AppShellRouteRouteImport.update({
  id: '/app-shell',
  path: '/app-shell',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const AppShellIndexRoute = AppShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppShellRouteRoute,
} as any)
const AppShellSectionRoute = AppShellSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AppShellRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app-shell': typeof AppShellRouteRouteWithChildren
  '/offline': typeof OfflineRoute
  '/app-shell/$section': typeof AppShellSectionRoute
  '/app-shell/': typeof AppShellIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/offline': typeof OfflineRoute
  '/app-shell/$section': typeof AppShellSectionRoute
  '/app-shell': typeof AppShellIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app-shell': typeof AppShellRouteRouteWithChildren
  '/offline': typeof OfflineRoute
  '/app-shell/$section': typeof AppShellSectionRoute
  '/app-shell/': typeof AppShellIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/app-shell' | '/offline' | '/app-shell/$section' | '/app-shell/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/offline' | '/app-shell/$section' | '/app-shell'
  id:
    | '__root__'
    | '/'
    | '/app-shell'
    | '/offline'
    | '/app-shell/$section'
    | '/app-shell/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppShellRouteRoute: typeof AppShellRouteRouteWithChildren
  OfflineRoute: typeof OfflineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-shell': {
      id: '/app-shell'
      path: '/app-shell'
      fullPath: '/app-shell'
      preLoaderRoute: typeof AppShellRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-shell/': {
      id: '/app-shell/'
      path: '/'
      fullPath: '/app-shell/'
      preLoaderRoute: typeof AppShellIndexRouteImport
      parentRoute: typeof AppShellRouteRoute
    }
    '/app-shell/$section': {
      id: '/app-shell/$section'
      path: '/$section'
      fullPath: '/app-shell/$section'
      preLoaderRoute: typeof AppShellSectionRouteImport
      parentRoute: typeof AppShellRouteRoute
    }
  }
}

interface AppShellRouteRouteChildren {
  AppShellSectionRoute: typeof AppShellSectionRoute
  AppShellIndexRoute: typeof AppShellIndexRoute
}

const AppShellRouteRouteChildren: AppShellRouteRouteChildren = {
  AppShellSectionRoute: AppShellSectionRoute,
  AppShellIndexRoute: AppShellIndexRoute,
}

const AppShellRouteRouteWithChildren = AppShellRouteRoute._addFileChildren(
  AppShellRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppShellRouteRoute: AppShellRouteRouteWithChildren,
  OfflineRoute: OfflineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
